---
- name: Deploy Lightweight Web App
  hosts: localhost
  connection: local
  become: yes
  tasks: 
    - name: Ensure Docker is running
      service: 
        name: docker
        state: started


    - name: Pull the latest Docker Image
      command: docker pull jaykona28/lightweight-app:latest
      # Replace <YOUR_DOCKERHUB_USERNAME> with your actual username
    
    - name: Stop existing container if running
      command: docker stop my-web-app
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm my-web-app
      ignore_errors: yes

    - name: Run the new container
      command: >
        docker run -d
        --name my-web-app
        -p 8080:80
        --memory="256m"
        --cpus="0.5"
         jaykona28/lightweight-app:latest

        
      
      
